forgejo-admin-password: ENC[AES256_GCM,data:O8TBMm0nzrteDmP31wNesg==,iv:JRdB36y3DDoXrh0KXgVKG8dijMqpInynC3xP/GjrAq4=,tag:9kmM2cJqfgfwRhqyzBvS7Q==,type:str]
forgejo-runner-token: ENC[AES256_GCM,data:H8m4+/Fe17kw61ZLb54yLq8QBewyx48f+Y/iyU0rhYIxWTZgOOdma2H8o/qW+g==,iv:4faNClBSDH5ymfYCaIXIuxlMji+gzjhS33YR/moaNF8=,tag:E2NUbKJnEiEJfPCjgGOTJw==,type:str]
bluesky-pds:
    env: ENC[AES256_GCM,data:oz7iN9gPWRblqa4MYgHqtiRhpBy2ss5MvLWWrBW+Nal4H5cMc5VXchcVgqrPookV+MrblXn/f5kOUdOv51VSnAMVVdDAu9nqmXBRP0mvHeiwCp2AttA0qOPlgxZMAQF9EgzSNP9N1MUCy3zYq4oSL+NsNdiGlviKPMMoKqhaKDCRtUUsEkZ7nFxkkj3Fw2scpAdWQqWae8xJKRDbbs7ON/TRl6lPL7vZpW+SCqBvuvAbj25AuiiOuFS40AJCGeCnnc67a5zJ0/z2EaTaCz/b5PI5RbU3g09uVtWa9ggVAap65hZ7j/Vr4QCxHyHVhoof0JB4re1tqHt/ZfwP40N8nJzXUNh0hvgTJT24g1AlRs7TVwLXp3tSQfcgRpc2QafpQSrdsg7/,iv:vw8jSnCilZsroF8A8+S1yrdpkQw6SwD63L32ZP4+ZW4=,tag:aPDDAENoDVyH8v8CsWsoPQ==,type:str]
sops:
    age:
        - recipient: age178aepfa5eyp45kche4z3pm59glmd7n5603vj9s4ytpvtgmdry33sw6r72m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVUNkRHJrNDNyUTRQQ2ow
            Rmt3S0xuVFVqVHdMZjZsSnFRdjNpZW9PYTJjCkV3cjlDSzZJRE53R2RRZ1BJTHpR
            UURVM1Bwbng0T050czdWM1Q2STNrUzQKLS0tIEo0S0JEZE1td3FGRTh4ZkR0elZo
            UzU0ckp1Y3lGdSt1dTBjQmpjTnNlUUUKMEmnMxJluLTE53Zp6ZeknRaKj5DpmWoy
            fVRIuaj9Tuwi/pyN2hPxzt8mTF3MkpQVekbeCkBkr1J7yqrtz/Rr4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T04:08:56Z"
    mac: ENC[AES256_GCM,data:ElGKgXRqrkFTb8IJN1/gbGy23zJ+ThV/1g+o+CvyJ7Kiff0ZFWdjTmOyO+86Yldd9Gweru8Wo0bFWA9GbOsbPk2owm/jZR9PTSQX0bf7c9Djbt1tnGXI74ecPhnSt7gxG90LaAV1voWrs+MYFD3cHprRtVz8rypuo1ozBB/65sg=,iv:SR+ok4trAmNVceqEWnxmZhxrLifklkKcewUt5vVPPvI=,tag:Jay+uu6Nt1tbmdCFa0d5hw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
