set -gx CARGO_HOME $XDG_DATA_HOME/cargo
set -gx GEM_HOME $XDG_DATA_HOME/gem
set -gx GEM_SPEC_CACHE $XDG_CACHE_HOME/gem
set -gx GHCUP_USE_XDG_DIRS yes
set -gx INPUTRC $XDG_CONFIG_HOME/readline/inputrc
set -gx LESSHISTFILE $XDG_STATE_HOME/less/history
set -gx NVM_DIR $XDG_DATA_HOME/nvm
set -gx RUSTUP_HOME $XDG_DATA_HOME/rustup
set -gx R_ENVIRON_USER $XDG_CONFIG_HOME/r/Renviron
set -gx STACK_XDG yes
set -gx WORKON_HOME $XDG_DATA_HOME/virtualenvs
